# Generated by Django 5.0.4 on 2025-01-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_chickens', models.IntegerField(default=20)),
                ('simulation_months', models.IntegerField(default=12)),
                ('average_eggs_per_laying', models.IntegerField(default=10)),
                ('simulation_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
