# Generated by Django 5.0.4 on 2025-01-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_chickensimulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoatSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_goats', models.IntegerField(default=10)),
                ('simulation_months', models.IntegerField(default=60)),
                ('average_kids_per_birth', models.IntegerField(default=2)),
                ('simulation_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
