# Generated by Django 5.0.4 on 2025-01-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_goatsimulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(choices=[('herd', 'Cow Herd'), ('chicken', 'Chicken Farm'), ('goat', 'Goat Farm')], max_length=10)),
                ('initial_count', models.IntegerField(default=10)),
                ('simulation_months', models.IntegerField(default=60)),
                ('average_per_cycle', models.IntegerField(default=2)),
                ('simulation_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChickenSimulation',
        ),
        migrations.DeleteModel(
            name='GoatSimulation',
        ),
        migrations.DeleteModel(
            name='HerdSimulation',
        ),
    ]
